//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnBoardingApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbOnboardingCCEntities : DbContext
    {
        public dbOnboardingCCEntities()
            : base("name=dbOnboardingCCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OBTActitud> OBTActitud { get; set; }
        public virtual DbSet<OBTActividadPrioritaria> OBTActividadPrioritaria { get; set; }
        public virtual DbSet<OBTAspectoTecnico> OBTAspectoTecnico { get; set; }
        public virtual DbSet<OBTEscalaCalificacion> OBTEscalaCalificacion { get; set; }
        public virtual DbSet<OBTEstadoEvaluacion> OBTEstadoEvaluacion { get; set; }
        public virtual DbSet<OBTEstadoProcesoColaborador> OBTEstadoProcesoColaborador { get; set; }
        public virtual DbSet<OBTPlantillaPuestoActividadPrioritaria> OBTPlantillaPuestoActividadPrioritaria { get; set; }
        public virtual DbSet<OBTPlantillaPuestoRecurso> OBTPlantillaPuestoRecurso { get; set; }
        public virtual DbSet<OBTProcesoColaborador> OBTProcesoColaborador { get; set; }
        public virtual DbSet<OBTProcesoColaboradorActitud> OBTProcesoColaboradorActitud { get; set; }
        public virtual DbSet<OBTProcesoColaboradorActividadPrioritaria> OBTProcesoColaboradorActividadPrioritaria { get; set; }
        public virtual DbSet<OBTProcesoColaboradorEvaluacion> OBTProcesoColaboradorEvaluacion { get; set; }
        public virtual DbSet<OBTProcesoColaboradorRecurso> OBTProcesoColaboradorRecurso { get; set; }
        public virtual DbSet<OBTRecurso> OBTRecurso { get; set; }
        public virtual DbSet<OBTResultadoEvaluacion> OBTResultadoEvaluacion { get; set; }
        public virtual DbSet<OBTResultadoCuadrante> OBTResultadoCuadrante { get; set; }
    }
}
