//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnBoardingApi.Models
{
    using System;
    
    public partial class OBPPlantillaConocimientoPorPuesto_Result1
    {
        public string CodigoPuestoLaboral { get; set; }
        public int CodigoActividadPrioritaria { get; set; }
        public string DescripcionAP { get; set; }
        public int CodigoAspectoTecnico { get; set; }
        public string Nombre { get; set; }
        public string DescripcionAST { get; set; }
    }
}
