//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnBoardingApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBTActividadPrioritaria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OBTActividadPrioritaria()
        {
            this.OBTPlantillaPuestoActividadPrioritaria = new HashSet<OBTPlantillaPuestoActividadPrioritaria>();
            this.OBTProcesoColaboradorActividadPrioritaria = new HashSet<OBTProcesoColaboradorActividadPrioritaria>();
        }
    
        public int CodigoActividadPrioritaria { get; set; }
        public int CodigoAspectoTecnico { get; set; }
        public string Descripcion { get; set; }
        public bool Activo { get; set; }
        public bool Eliminado { get; set; }
        public string UsuarioInserto { get; set; }
        public System.DateTime FechaInserto { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
    
        public virtual OBTAspectoTecnico OBTAspectoTecnico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OBTPlantillaPuestoActividadPrioritaria> OBTPlantillaPuestoActividadPrioritaria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OBTProcesoColaboradorActividadPrioritaria> OBTProcesoColaboradorActividadPrioritaria { get; set; }
    }
}
