//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnBoardingApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBTProcesoColaboradorEvaluacion
    {
        public int CodigoProcesoColaboradorEvaluacion { get; set; }
        public int CodigoProcesoColaborador { get; set; }
        public int CodigoEstadoEvaluacion { get; set; }
        public int NoEvaluacion { get; set; }
        public decimal PunteoConocimiento { get; set; }
        public decimal PunteoWill { get; set; }
        public Nullable<int> CodigoResultadoEvaluacion { get; set; }
        public bool Activo { get; set; }
        public bool Eliminado { get; set; }
        public string UsuarioInserto { get; set; }
        public System.DateTime FechaInserto { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
    
        public virtual OBTEstadoEvaluacion OBTEstadoEvaluacion { get; set; }
        public virtual OBTProcesoColaborador OBTProcesoColaborador { get; set; }
        public virtual OBTResultadoEvaluacion OBTResultadoEvaluacion { get; set; }
    }
}
