//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnBoardingApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBTProcesoColaborador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OBTProcesoColaborador()
        {
            this.OBTProcesoColaboradorActitud = new HashSet<OBTProcesoColaboradorActitud>();
            this.OBTProcesoColaboradorActividadPrioritaria = new HashSet<OBTProcesoColaboradorActividadPrioritaria>();
            this.OBTProcesoColaboradorEvaluacion = new HashSet<OBTProcesoColaboradorEvaluacion>();
            this.OBTProcesoColaboradorRecurso = new HashSet<OBTProcesoColaboradorRecurso>();
        }
    
        public int CodigoProcesoColaborador { get; set; }
        public string CodigoColaborador { get; set; }
        public string NombreColaborador { get; set; }
        public string CodigoPuestoLaboral { get; set; }
        public string NombrePuestoLaboral { get; set; }
        public int NoEvaluaciones { get; set; }
        public System.DateTime FechaInicioProceso { get; set; }
        public int CodigoEstadoProcesoColaborador { get; set; }
        public bool Activo { get; set; }
        public bool Eliminado { get; set; }
        public string UsuarioInserto { get; set; }
        public System.DateTime FechaInserto { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
    
        public virtual OBTEstadoProcesoColaborador OBTEstadoProcesoColaborador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OBTProcesoColaboradorActitud> OBTProcesoColaboradorActitud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OBTProcesoColaboradorActividadPrioritaria> OBTProcesoColaboradorActividadPrioritaria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OBTProcesoColaboradorEvaluacion> OBTProcesoColaboradorEvaluacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OBTProcesoColaboradorRecurso> OBTProcesoColaboradorRecurso { get; set; }
    }
}
